### ISSUE TITLE
Responsive issue in Nav element

### ISSUE THREAD

**Issue by RohanJacob23** [creativecommons/creativecommons.github.io-source#725]
## Description
When in mobile view, the navigation bar is overflowing due to excessive padding.

## Reproduction
1. Go to [Creative Commons Opensource](https://opensource.creativecommons.org/) in mobile view
2. see the nav element overflowing from the html element

## Expectation
The nav element should not be overflowing from html element and it should be responsive.

## Screenshots
![Screenshot from 2023-07-10 16-35-28](https://github.com/creativecommons/creativecommons.github.io-source/assets/97782641/d08effdc-b71c-42cf-be58-3a2063dba9cd)

![Screenshot from 2023-07-10 16-37-24](https://github.com/creativecommons/creativecommons.github.io-source/assets/97782641/5c710cd7-cab8-4a27-a2d4-a181a182b05d)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
To clarify the above since the photo might not explain this detail fully, on smaller viewports the "hamburger" icon has spacing between itself and the right edge of the viewport.
<img width="434" alt="Screen Shot 2023-07-10 at 2 21 16 PM" src="https://github.com/creativecommons/creativecommons.github.io-source/assets/109087089/f3763342-3231-4b5c-8585-8e64ec8c1d98">



However, on much smaller viewports, due to the fact that the logo doesn't narrow in some way (padding, size, etc.). This occurs.

<img width="345" alt="Screen Shot 2023-07-10 at 2 21 00 PM" src="https://github.com/creativecommons/creativecommons.github.io-source/assets/109087089/7fde6b99-f4c1-4cd0-b2dd-4183e4cace84">

The expectation would be that some degree or right edge padding exist between the "hamburger" and the viewport edge and that elements further to the left narrow in some fashion.

**Comment by RohanJacob23** [comment]
### Solution that I have thought of:

1. Set the width of the SVG to 100%. By doing this, the logo won't occupy the entire space of the navbar flex, avoiding overflow issues with the hamburger icon.

![Screenshot from 2023-07-11 16-03-15](https://github.com/creativecommons/creativecommons.github.io-source/assets/97782641/d0f21c1e-1fff-47bf-88f8-36554b41fa93)

2. Adjust the padding from `padding: 2rem` to `padding: 2rem 0.5rem`. This decreases the left and right padding, preventing the logo from becoming too small and improving the mobile view.

![Screenshot from 2023-07-11 16-02-56](https://github.com/creativecommons/creativecommons.github.io-source/assets/97782641/c17d859f-98a3-436f-88c8-507255000452)


### The output would something like this:
![Screenshot from 2023-07-11 16-02-31](https://github.com/creativecommons/creativecommons.github.io-source/assets/97782641/f67c1ef6-36c1-47ef-b8a2-68cec2013d38)

**Comment by RohanJacob23** [comment]
Hi @possumbilities,

Could you please guide me a bit on how to add styling?

**Comment by RohanJacob23** [comment]
Hi @possumbilities,

Is it okay if I can complete the task by Monday or Tuesday?

**Comment by possumbilities** [comment]
@RohanJacob23 That's absolutely fine! ❤️

**Comment by RohanJacob23** [comment]
Hello @possumbilities,

### I am facing this error:-

`Traceback (most recent call last):
  File "C:\Users\rohan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rohan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\Scripts\lektor.EXE\__main__.py", line 7, in <module>
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\lektor\cli.py", line 622, in main
    cli.main(args=args, prog_name=name)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\click\decorators.py", line 93, in new_func        
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\lektor\cli.py", line 342, in server_cmd
    ctx.load_plugins(extra_flags=extra_flags)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\lektor\cli_utils.py", line 135, in load_plugins   
    load_packages(self.get_env(extra_flags=extra_flags), reinstall=reinstall)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\lektor\packages.py", line 290, in load_packages   
    update_cache(
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\lektor\packages.py", line 251, in update_cache    
    click.echo("Updating packages in %s for project" % package_root)
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\click\utils.py", line 314, in echo
    file = auto_wrap_for_ansi(file)  # type: ignore
  File "C:\Users\rohan\.virtualenvs\creativecommons.github.io-source-OHAFjTLf\lib\site-packages\click\_compat.py", line 533, in auto_wrap_for_ansi
    import colorama
ModuleNotFoundError: No module named 'colorama'`

Could please guide me.

**Comment by possumbilities** [comment]
@RohanJacob23 what command or activity is causing this error? Could you share that as well?

**Comment by RohanJacob23** [comment]
pipenv install --dev

**Comment by RohanJacob23** [comment]
Yes i did

**Comment by possumbilities** [comment]
@RohanJacob23 I'll look into it further. We're starting to stray from the topic here. 

You might be better served by joining the Dev community on the [CC Community Slack](https://opensource.creativecommons.org/community/#slack) and asking for help there.

Or making a new Issue about this setup error, documenting it fully, and proceeding from there.

**Comment by NayanAnsh** [comment]
I would like to work on this issue.

**Comment by possumbilities** [comment]
@NayanAnsh If you'd like to give it a try, sure.

**Comment by wasimapinjari** [comment]
@possumbilities CSS needs some heavy fixing is it possible to fix the CSS and then substitute the fixed version in CDN?

As you can see the footer has some problems:

The alignment is off, there is unnecessary spacing creating a bad responsive design, if I type the wrong email there are no indicators for any errors (no error handling), and the LinkedIn icon is odd-man-out it should be a circle as well and it would be nice if you add a GitHub icon next to it for people to find this open-source project easily.

![Screenshot (221)](https://github.com/creativecommons/creativecommons.github.io-source/assets/95426296/8f05d635-f604-4c14-97dc-d1ae27bd1b7a)

**Comment by namanbarkiya** [comment]
Hey, @possumbilities Could you kindly review the pull request? There hasn't been any activity since Aug 3, so I attempted to fix it without being formally assigned.
